
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NahID
 */
public class C2 extends javax.swing.JFrame {

    /**
     * Creates new form C2
     */
    DB db = new DB();
    ResultSet rs;
    Connection conn=null;
    Statement st=null;
    public C2() {
        initComponents();
        upTable3();
    }
    public void upTable3(){
        try{
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            Statement st = conn.createStatement();
            String sql="SELECT * FROM c1";
            ResultSet rs = st.executeQuery(sql);
            DefaultTableModel model = new DefaultTableModel(new String[]{"c1", "c2", "c3" , "c4" , "cid"}, 0);
            while(rs.next())
            {
                String col1 = rs.getString("c1");
                String col2 = rs.getString("c2");
                String col3 = rs.getString("c3"); 
                String col4 = rs.getString("c4");
                String col5 = rs.getString("cid"); 
                model.addRow(new Object[]{col1, col2, col3, col4, col5});
            }
            jTable1.setModel(model);
           }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
                }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jBuExit = new javax.swing.JButton();
        jTeC1 = new javax.swing.JTextField();
        jTeC2 = new javax.swing.JTextField();
        jTeC3 = new javax.swing.JTextField();
        jTeC4 = new javax.swing.JTextField();
        jTeCid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBuRefresh = new javax.swing.JButton();
        jBuAdd = new javax.swing.JButton();
        jBuDelete = new javax.swing.JButton();
        jBuBack = new javax.swing.JButton();
        jBuClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setBackground(new java.awt.Color(153, 153, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel1.setText("Available Courses:");

        jBuExit.setBackground(new java.awt.Color(204, 0, 0));
        jBuExit.setForeground(new java.awt.Color(255, 255, 255));
        jBuExit.setText("Exit");
        jBuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuExitActionPerformed(evt);
            }
        });

        jTeC1.setBackground(new java.awt.Color(102, 102, 102));
        jTeC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTeC1ActionPerformed(evt);
            }
        });

        jTeC2.setBackground(new java.awt.Color(102, 102, 102));

        jTeC3.setBackground(new java.awt.Color(102, 102, 102));

        jTeC4.setBackground(new java.awt.Color(102, 102, 102));

        jTeCid.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setText("C1:");

        jLabel3.setText("C2:");

        jLabel4.setText("C4:");

        jLabel5.setText("CID:");

        jLabel6.setText("C3:");

        jBuRefresh.setBackground(new java.awt.Color(0, 102, 102));
        jBuRefresh.setText("Refresh");
        jBuRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuRefreshActionPerformed(evt);
            }
        });

        jBuAdd.setBackground(new java.awt.Color(51, 51, 51));
        jBuAdd.setForeground(new java.awt.Color(255, 255, 255));
        jBuAdd.setText("ADD");
        jBuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuAddActionPerformed(evt);
            }
        });

        jBuDelete.setBackground(new java.awt.Color(255, 0, 0));
        jBuDelete.setForeground(new java.awt.Color(255, 255, 255));
        jBuDelete.setText("Delete");
        jBuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuDeleteActionPerformed(evt);
            }
        });

        jBuBack.setBackground(new java.awt.Color(51, 51, 51));
        jBuBack.setForeground(new java.awt.Color(255, 255, 255));
        jBuBack.setText("Back");
        jBuBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuBackActionPerformed(evt);
            }
        });

        jBuClose.setBackground(new java.awt.Color(153, 153, 153));
        jBuClose.setForeground(new java.awt.Color(0, 0, 0));
        jBuClose.setText("Close");
        jBuClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTeC1)
                            .addComponent(jTeC2)
                            .addComponent(jTeC3)
                            .addComponent(jTeC4)
                            .addComponent(jTeCid, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addComponent(jBuAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBuBack)
                        .addGap(33, 33, 33)
                        .addComponent(jBuClose)
                        .addGap(44, 44, 44)
                        .addComponent(jBuExit)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jBuDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBuRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBuDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBuRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTeC1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTeC2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTeC3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTeC4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTeCid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(jBuAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBuExit)
                    .addComponent(jBuBack)
                    .addComponent(jBuClose)))
        );

        setBounds(500, 500, 751, 442);
    }// </editor-fold>//GEN-END:initComponents

    private void jBuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuExitActionPerformed
        System.exit(0);         this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jBuExitActionPerformed

    private void jTeC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTeC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTeC1ActionPerformed

    private void jBuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuAddActionPerformed
         try{
             DB db = new DB();
            if(!jTeC1.getText().equals("") && !jTeC2.getText().equals("") && !jTeC3.getText().equals("")){
            db.theQuery("insert into c1 (c1,c2,c3,c4,cid)values('"+jTeC1.getText()+"','"+jTeC2.getText()+"','"+jTeC3.getText()+"','"+jTeC4.getText()+"','"+jTeCid.getText()+"')");
        }
        else{
            JOptionPane.showMessageDialog(null,"Error! Please Fill Up All of the Fields");
        }
    }catch(Exception ex){
        JOptionPane.showMessageDialog(null, ex.getMessage());
    }            // TODO add your handling code here:
    }//GEN-LAST:event_jBuAddActionPerformed

    private void jBuRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuRefreshActionPerformed
        jTeC1.setText("");
        jTeC2.setText("");
        jTeC3.setText("");
        jTeC4.setText("");
        jTeCid.setText("");
        upTable3();         // TODO add your handling code here:
    }//GEN-LAST:event_jBuRefreshActionPerformed

    private void jBuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuDeleteActionPerformed
        if(jTable1.getSelectedRow()==-1){
        if(jTable1.getSelectedRow()==0){
            JOptionPane.showMessageDialog(null,"Table is empty!!");
           }
        else{
            JOptionPane.showMessageDialog(null,"Please Select a Course List!");
        }
    }
        else{
            int selectedRowIndex = jTable1.getSelectedRow();
            db.theQuery("delete from c1 where c1="+jTable1.getModel().getValueAt(selectedRowIndex, 1));
    }              // TODO add your handling code here:
    }//GEN-LAST:event_jBuDeleteActionPerformed

    private void jBuCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuCloseActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBuCloseActionPerformed

    private void jBuBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuBackActionPerformed
        this.dispose();
        new Home1().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jBuBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new C2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBuAdd;
    private javax.swing.JButton jBuBack;
    private javax.swing.JButton jBuClose;
    private javax.swing.JButton jBuDelete;
    private javax.swing.JButton jBuExit;
    private javax.swing.JButton jBuRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTeC1;
    private javax.swing.JTextField jTeC2;
    private javax.swing.JTextField jTeC3;
    private javax.swing.JTextField jTeC4;
    private javax.swing.JTextField jTeCid;
    // End of variables declaration//GEN-END:variables
}
